### PR TITLE
Replace `Buffer` with `b4a`

### PR DESCRIPTION
**Pull request by kasperisager**

### CODE REVIEW

**Comment by Nazeh** [comment]
`turbo-hash-map` is not "unbuffered", so it throws ` t.key.equals is not a function`

**Comment by kasperisager** [comment]
Ah, good catch! I'll open a PR.

**Comment by mafintosh** [comment]
@kasperisager can we split this into two PRs? One for turbo and one for b4a?

**Comment by mafintosh** [comment]
Ya b4a first, because I'm unsure if we'll land turbo anytime soon. Benchmarks showed some weird behaivour that we have to investigate, so don't want that to hold up b4a

**Comment by kasperisager** [comment]
@mafintosh All set!

**Comment by kasperisager** [comment]
The tests are stalling on Windows for some reason 🤔

**Pull request merged**
